easy_admin:
  entities:
    # change the following to the namespaces of your own entities
    - App\Entity\Website
    - App\Entity\Apps
    - App\Entity\Software
  user:
    display_name: true
  design:
    brand_color: '#3B5163'

